# Generated by Django 4.2.7 on 2026-04-05 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('AC', 'Активная'), ('FR', 'Заморожена'), ('PO', 'Потенциальная')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BE', 'Бюджет превышен'), ('GR', 'Цель достигнута'), ('GD', 'Скоро дедлайн'), ('RC', 'Регулярный платёж'), ('OT', 'Другое')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('D', 'Каждый день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц'), ('Y', 'Раз в год')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to=settings.AUTH_USER_MODEL),
        ),
    ]
