# Generated by Django 6.0.5 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_status_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название банка')),
                ('color', models.CharField(default='#2c8a93', max_length=20, verbose_name='Цвет (HEX)')),
                ('logo_name', models.CharField(default='default_bank.png', max_length=100, verbose_name='Файл иконки')),
            ],
            options={
                'verbose_name': 'Доступный банк',
                'verbose_name_plural': 'Доступные банки',
            },
        ),
        migrations.CreateModel(
            name='AvailableCategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('IN', 'Доход'), ('EX', 'Расход'), ('BO', 'Оба')], default='BO', max_length=2)),
                ('color', models.CharField(default='#2c8a93', max_length=20, verbose_name='Цвет темы')),
                ('icon_name', models.CharField(default='wallet1.png', max_length=100, verbose_name='Файл иконки')),
            ],
            options={
                'verbose_name': 'Шаблон категории',
                'verbose_name_plural': 'Шаблоны категорий',
            },
        ),
    ]
