# Generated by Django 6.0.5 on 2026-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availablebank_availablecategorytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BE', 'Бюджет превышен'), ('GR', 'Цель достигнута'), ('GD', 'Скоро дедлайн'), ('RC', 'Регулярный платёж'), ('OT', 'Другое')], default='OT', max_length=2),
        ),
    ]
