# Generated by Django 6.0.5 on 2026-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_title_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, default='Не указан', max_length=100, null=True),
        ),
    ]
