# Generated by Django 6.0.5 on 2026-06-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.availablebank'),
        ),
    ]
