# Generated by Django 6.0.5 on 2026-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_account_bank_name_account_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablebank',
            name='color',
        ),
        migrations.RemoveField(
            model_name='availablebank',
            name='logo_name',
        ),
        migrations.RemoveField(
            model_name='availablecategorytemplate',
            name='color',
        ),
        migrations.AddField(
            model_name='availablebank',
            name='color_hex',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет (HEX)'),
        ),
        migrations.AddField(
            model_name='availablecategorytemplate',
            name='color_hex',
            field=models.CharField(default='#2c8a93', max_length=7, verbose_name='Цвет темы (HEX)'),
        ),
        migrations.AlterField(
            model_name='availablebank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='availablecategorytemplate',
            name='icon_name',
            field=models.CharField(default='wallet1.png', max_length=100, verbose_name='Имя файла иконки'),
        ),
        migrations.AlterField(
            model_name='availablecategorytemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='availablecategorytemplate',
            name='type',
            field=models.CharField(choices=[('EX', 'Ежемесячные траты / Накопления'), ('GL', 'Бессрочная цель'), ('IN', 'Доход')], default='EX', max_length=2, verbose_name='Тип по умолчанию'),
        ),
    ]
