# Generated by Django 6.0.5 on 2026-06-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_availablebank_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.availablecategorytemplate'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('IN', 'Доход'), ('EX', 'Расход'), ('BO', 'Оба'), ('GL', 'Бессрочная цель')], default='BO', max_length=2),
        ),
    ]
