# Generated by Django 6.0.5 on 2026-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_template_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
