# Generated by Django 6.0.5 on 2026-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
